# Generated by Django 5.0 on 2024-04-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('pID', models.IntegerField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('quadrant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('exID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PointResult',
            fields=[
                ('resID', models.IntegerField(primary_key=True, serialize=False)),
                ('seen', models.BooleanField()),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.examination')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.point')),
            ],
        ),
    ]
