# Generated by Django 5.0.1 on 2024-11-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patID', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('pID', models.IntegerField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('quadrant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('exID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('P', 'Perimetry'), ('I', 'Ishihara')], default=None, max_length=1)),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ResultIshihara',
            fields=[
                ('resID', models.AutoField(primary_key=True, serialize=False)),
                ('recognized', models.BooleanField()),
                ('filename', models.CharField(max_length=50)),
                ('ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.examination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultPerimetry',
            fields=[
                ('resID', models.AutoField(primary_key=True, serialize=False)),
                ('seen', models.BooleanField()),
                ('ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.examination')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.point')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
