# Generated by Django 5.0 on 2024-04-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='id',
            new_name='patID',
        ),
    ]
