# Generated by Django 5.0 on 2024-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_id_patient_patid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='pID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
