# Generated by Django 5.0 on 2024-04-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_patient_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='patientID',
            new_name='patID',
        ),
        migrations.RenameField(
            model_name='pointresult',
            old_name='examinationID',
            new_name='exID',
        ),
        migrations.RenameField(
            model_name='pointresult',
            old_name='pointID',
            new_name='pID',
        ),
    ]
