# Generated by Django 5.0 on 2024-04-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_rename_patientid_examination_patid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='patID',
            new_name='pat',
        ),
        migrations.RenameField(
            model_name='pointresult',
            old_name='exID',
            new_name='ex',
        ),
        migrations.RenameField(
            model_name='pointresult',
            old_name='pID',
            new_name='p',
        ),
    ]
