# Generated by Django 5.0.1 on 2024-05-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_rename_patid_examination_pat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='pID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
