# Generated by Django 5.0.1 on 2024-11-04 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_point_pid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointResult',
            new_name='ResultPerimetry',
        ),
        migrations.AddField(
            model_name='examination',
            name='type',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ResultIshihara',
            fields=[
                ('resID', models.AutoField(primary_key=True, serialize=False)),
                ('recognized', models.BooleanField()),
                ('filename', models.CharField(max_length=50)),
                ('ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.examination')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
