# Generated by Django 5.0.1 on 2024-11-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_rename_pointresult_resultperimetry_examination_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
